platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'testSipPhone' do

# pod 'pjsip', :git => 'https://github.com/chebur/pjsip.git', :commit => '890929be9d82900cba8996427725794a244725b5'
pod 'pjsip', :path => '/Users/Star/work/icsoc/cocoapods/pjsip/'

end